# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='apellido',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='comentario',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='nombre',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
